(
    SETTINGS,
    SETTINGS_BACK,
    SETTINGS_ACCOUNT,
    SETTINGS_ACCOUNT_BACK,
    SETTINGS_ACCOUNT_DELETE,
    SETTINGS_ACCOUNT_DELETE_CANCEL,
    SETTINGS_ACCOUNT_DELETE_CONFIRM,
) = map(chr, range(800, 807))