currencies = [
    (':ar:', 'ARS'),
    (':bo:', 'BOB'),
    (':br:', 'BRL'),
    (':cl:', 'CLP'),
    (':co:', 'COP'),
    (':cr:', 'CRC'),
    (':cu:', 'CUP'),
    (':do:', 'DOP'),
    (':sv:', 'SVC'),
    (':gt:', 'GTQ'),
    (':ht:', 'HTG'),
    (':hn:', 'HNL'),
    (':mx:', 'MXN'),
    (':ni:', 'NIO'),
    (':pa:', 'PAB'),
    (':py:', 'PYG'),
    (':pe:', 'PEN'),
    (':uy:', 'UYU'),
    (':ve:', 'VES'),
    (':us:', 'USD'),
    (':cn:', 'CNY')
]